# docker-compose.yml
version: '3.4'

x-cache:
  &cache
  cache_from:
    - ${CONTAINER_REGISTRY_BASE}/php
    - ${CONTAINER_REGISTRY_BASE}/nginx
    - ${CONTAINER_REGISTRY_BASE}/varnish

x-network:
  &network
  networks:
    - api_platform_network

services:
# Uncomment these lines only if you want to run one api-platform instance using traefik
  traefik:
    image: traefik:v2.1.0-rc2
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--metrics"
      - "--metrics.prometheus.buckets=0.1,0.3,1.2,5.0"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    labels:
      - traefik.enable=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    <<: *network
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "5m"


  php:
    image: ${CONTAINER_REGISTRY_BASE}/php
    build:
      context: ./api
      target: api_platform_php
      <<: *cache
    depends_on: 
      - db
    environment:
      # You should remove these variables from .env into api folder
      - TRUSTED_HOSTS=^(((${SUBDOMAINS_LIST}\.)?${DOMAIN_NAME})|api)$$
      - CORS_ALLOW_ORIGIN=^${HTTP_OR_SSL}(${SUBDOMAINS_LIST}.)?${DOMAIN_NAME}$$
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASS}@db/${DB_NAME}
      - MERCURE_SUBSCRIBE_URL=${HTTP_OR_SSL}mercure.${DOMAIN_NAME}$$
      - MERCURE_PUBLISH_URL=${HTTP_OR_SSL}mercure.${DOMAIN_NAME}$$
      - MERCURE_JWT_SECRET=${JWT_KEY}
      - APP_SECRET=${JWT_KEY}
      - ELASTICSEARCH_HOST=${HTTP_OR_SSL}localhost:9200
    expose:
      - 9200
    volumes:
      - ./api:/srv/api:rw,cached
    <<: *network
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "5m"

  api:
    image: ${CONTAINER_REGISTRY_BASE}/nginx
    build:
      context: ./api
      target: api_platform_nginx
      <<: *cache
    depends_on:
      - php
    volumes:
      - ./api/public:/srv/api/public:ro
    labels:
      - traefik.http.routers.api.rule=Host(`api.${DOMAIN_NAME}`)
      - traefik.enable=true
    <<: *network
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "5m"

  cache-proxy:
    image: ${CONTAINER_REGISTRY_BASE}/varnish
    build:
      context: ./api
      target: api_platform_varnish
      <<: *cache
    depends_on:
      - api
    volumes:
      - ./api/docker/varnish/conf:/usr/local/etc/varnish:ro
    tmpfs:
      - /usr/local/var/varnish:exec
    labels:
      - traefik.http.routers.cache-proxy.rule=Host(`cache.${DOMAIN_NAME}`)
      - traefik.enable=true
    <<: *network
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "5m"

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    <<: *network
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "5m"

  mercure:
    image: dunglas/mercure
    environment:
      - JWT_KEY=${JWT_KEY}
      - ALLOW_ANONYMOUS=0
      - CORS_ALLOWED_ORIGINS=^${HTTP_OR_SSL}(${SUBDOMAINS_LIST}.)?${DOMAIN_NAME}$$
      - PUBLISH_ALLOWED_ORIGINS=${HTTP_OR_SSL}
      - DEMO=1
    labels:  
      - traefik.enable=true
      - traefik.backend=mercure
      - traefik.http.routers.mercure.rule=Host(`mercure.${DOMAIN_NAME}`)
      - traefik.http.routers.mercure.service=mercure@internal
      - traefik.http.routers.mercure.middlewares=auth
      - traefik.http.middlewares.auth.basicauth.users=${MERCURE_HTACCESS}
      - traefik.frontend.rule=Host:mercure.test
    <<: *network
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "5m"

  client:
    image: ${CONTAINER_REGISTRY_BASE}/client
    build:
      context: ./client
      cache_from:
        - ${CONTAINER_REGISTRY_BASE}/client
    volumes:
      - ./client:/usr/src/client:rw,cached
      - /usr/src/client/node_modules
    expose:
      - 3000
    ports:
      - target: 3000
    labels:
      - traefik.http.routers.client.rule=Host(`${DOMAIN_NAME}`)
      - traefik.enable=true
      - traefik.port=3000
    environment:
      # You should remove this variable from .env into client folder
      - REACT_APP_API_ENTRYPOINT=${HTTP_OR_SSL}www.${DOMAIN_NAME}
    <<: *network
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "5m"

  admin:
    image: ${CONTAINER_REGISTRY_BASE}/admin
    build:
      context: ./admin
      cache_from:
        - ${CONTAINER_REGISTRY_BASE}/admin
    environment:
      # You should remove this variable from .env into admin folder
      - REACT_APP_API_ENTRYPOINT=${HTTP_OR_SSL}admin.${DOMAIN_NAME}
    labels:  
      - traefik.enable=true
      - traefik.backend=admin
      - traefik.http.routers.admin.rule=Host(`admin.${DOMAIN_NAME}`)
      - traefik.http.routers.admin.service=admin@internal
      - traefik.http.routers.admin.middlewares=auth
      - traefik.http.middlewares.auth.basicauth.users=${ADMIN_HTACCESS}
      - traefik.frontend.rule=Host:admin.test
    volumes:
      - ./admin:/usr/src/admin:rw,cached
      - /usr/src/admin/node_modules
    ports:
      - target: 3000
        published: 81
        protocol: tcp
    <<: *network
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "5m"

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    container_name: es01
    environment:
      - node.name=es01
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    labels:  
      - traefik.enable=true
      - traefik.backend=es01
      - traefik.http.routers.es01.rule=Host(`elastic-api.${DOMAIN_NAME}`)
      - traefik.port=9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    <<: *network
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "5m"

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    container_name: es02
    environment:
      - node.name=es02
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    labels:  
      - traefik.enable=true
      - traefik.backend=es02
      - traefik.http.routers.es02.rule=Host(`elastic-api2.${DOMAIN_NAME}`)
      - traefik.port=9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata02:/usr/share/elasticsearch/data
    <<: *network
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "5m"

  # Access Kibana at http://localhost:5601  without Traefik
  # Access Kibana at http://kibana.test (if using Traefik)
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.3.1  # must match elasticsearch image
    labels:  
      - traefik.enable=true
      - traefik.backend=kibana
      - traefik.http.routers.kibana.rule=Host(`kibana.${DOMAIN_NAME}`)
      - traefik.http.routers.kibana.service=kibana@internal
      - traefik.http.routers.kibana.middlewares=auth
      - traefik.http.middlewares.auth.basicauth.users=${KIBANA_HTACCESS}
      - traefik.frontend.rule=Host:kibana.test
      - traefik.port=5601
    environment:
      - SERVER_NAME=kibana.local
      - ELASTICSEARCH_HOSTS=http://es01:9200
      - xpack.security.enabled=false
    ports:
      - 5601:5601
    links:
      - es01:elasticsearch
      - es02:elasticsearch
    depends_on:
      - es01
      - es02
    <<: *network
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "5m"

  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:6.6.2
    volumes:
      - ./logstash/pipeline/:/usr/share/logstash/pipeline/
      - ./logstash/:/usr/share/logstash/config/
      - ./logstash/patterns:/etc/logstash/patterns
      - ./logstash/templates:/etc/logstash/templates
      - ./logstash/conf.d/:/etc/logstash/conf.d/
    labels:  
      - traefik.enable=true
      - traefik.backend=logstash
      - traefik.http.routers.logstash.rule=Host(`logstash.${DOMAIN_NAME}`)
      - traefik.http.routers.logstash.service=logstash@internal
      - traefik.http.routers.logstash.middlewares=auth
      - traefik.http.middlewares.auth.basicauth.users=${LOGSTASH_HTACCESS}
      - traefik.frontend.rule=Host:logstash.test
    ports:
      - "5044:5044"
      - "5000:5000"
      - "5001:5002"
      - "5002:5002"
      - "9600:9600"
    links:
      - es01
      - es02
    environment:
      - "LS_JAVA_OPTS=-Xmx256m -Xms256m"
    <<: *network
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "5m"

#  graylog_mongo:
#    image: mongo:4
#    container_name: graylog_mongo
#    restart: always
#    labels:
#      - "traefik.enable=false"
#    volumes:
#      - "graylog_mongo:/data/db"
#    <<: *network
#    logging:
#      driver: "json-file"
#      options:
#        max-file: "1"
#        max-size: "5m"

#  graylog:
#    image: graylog/graylog:3.1.0
#    container_name: graylog
#    volumes:
#      - "graylog_graylog-data:/usr/share/graylog/data/journal"
#      - "graylog_graylog-config:/usr/share/graylog/data/config"
#    restart: always
#    env_file:
#      - ./graylog.env
#    labels:
#      - traefik.backend=graylog
#      - traefik.docker.network=compose_frontend
#      - traefik.port=9000"
#      - traefik.frontend.entryPoints=http,https
#      - traefik.http.routers.logstash.rule=Host(`graylog.${DOMAIN_NAME}`)
#      - traefik.frontend.rule=Host:graylog.test
#    depends_on:
#      - graylog_mongo
#      - es01
#      - es02
#    links:
#      - graylog_mongo:mongo
#      - es01:elasticsearch
#      - es02:elasticsearch
#    <<: *network
#    ports:
#      - "12201:12201/udp"
#    logging:
#      driver: "json-file"
#      options:
#        max-file: "1"
#        max-size: "5m"

  grafana:
    image: grafana/grafana
    environment:
      - GF_SERVER_DOMAIN=grafana.${DOMAIN_NAME}
      - GF_SERVER_ROOT_URL=${HTTP_OR_SSL}grafana.${DOMAIN_NAME}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_METRICS_ENABLED=true
      - GF_METRICS_BASIC_AUTH_USERNAME=${GRAFANA_USERNAME}
      - GF_METRICS_BASIC_AUTH_PASSWORD=${GRAFANA_PASSWORD}
      - GF_ANALYTICS_REPORTING_ENABLED=false
      - GF_INSTALL_PLUGINS=${GRAFANA_PLUGINS}
    volumes:
      - grafana:/var/lib/grafana
    <<: *network
    labels:
      - traefik.enable=true
      - traefik.port=3001
      - traefik.http.routers.grafana.rule=Host(`grafana.${DOMAIN_NAME}`)
      - traefik.frontend.rule=Host:grafana.local
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "5m"

volumes:
  db-data: {}
  esdata01:
    driver: local
  esdata02:
    driver: local
  grafana:
  graylog_mongo:
  graylog_graylog-data:
  graylog_graylog-config:

networks:
  api_platform_network:
    external: true