  
debug = false

logLevel = "ERROR"
defaultEntryPoints = ["https"]

[web]
  address = ":8088"
  [web.statistics]

[entryPoints]
  [entryPoints.https]
    address = ":443"

[metrics]
  [metrics.prometheus]

################################################################
# Docker configuration backend
################################################################
[docker]

endpoint = "unix:///var/run/docker.sock"
domain = "docker.localhost"
watch = true

# Expose containers by default in traefik
exposedbydefault = false

# Use Swarm Mode services as data provider
swarmmode = false